In [1]:
!pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 1.7 MB/s eta 0:00:08
   --- ------------------------------------ 1.0/12.8 MB 2.0 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.8 MB 3.0 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.8 MB 3.2 MB/s eta 0:00:04
   ----------- ---------------------------- 3.7/12.8 MB 3.4 MB/s eta 0:00:03
   -------------- ------------------------- 4.7/12.8 MB 3.8 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.8 MB 3.7 MB/s eta 0:00:02
   -------------------- ------------------- 6.6/12.8 MB 3.9 MB/s eta 0:00:02
   ------------------------ --------------- 7.9/12.8 MB 4.1 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.8 MB 4.2 MB/s eta 0:00:01
   ------------------------------ --------- 9.7/12.8 MB 4.3 MB/s eta 0:00:01
   ----------

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
keras 3.9.1 requires h5py, which is not installed.
keras 3.9.1 requires rich, which is not installed.
tensorboard 2.19.0 requires markdown>=2.6.8, which is not installed.
tensorboard 2.19.0 requires protobuf!=4.24.0,>=3.19.6, which is not installed.
tensorboard 2.19.0 requires werkzeug>=1.0.1, which is not installed.
tensorflow 2.19.0 requires h5py>=3.11.0, which is not installed.
tensorflow 2.19.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3, which is not installed.
tensorflow 2.19.0 requires requests<3,>=2.21.0, which is not installed.
tensorflow 2.19.0 requires typing-extensions>=3.6.6, which is not installed.
tensorflow 2.19.0 requires wrapt>=1.11.0, which is not installed.
tensorflow 2.19.0 requires numpy<2.2.0,>=1.26.0, but you have numpy 2.3.2 which is incompatib

In [2]:
import numpy as np 
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
arr1.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [10]:
np.arange(0,12,2).reshape(3,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [11]:
arr3 = np.array([1,2,3,4,5])
arr4 = np.array([6,7,8,9,10]) 

print(arr3+arr4)
print(arr3-arr4)
print(arr3*arr4)
print(arr3/arr4)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [15]:
data = np.array([1,2,3,4,5])

mean = np.mean(data)
std = np.std(data)

normalization = (data-mean)/std

print(mean)
print(normalization)
print(std)

3.0
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
1.4142135623730951
